# Unidad 8: Paquete Numpy

+ Es el paquete fundamental para la computación científica y el manejo de <span style="color:magenta">arrays</span> numéricos multidimensionales.

+ La información del paquete junto con las instrucciones de instalación se pueden encontrar en [Numpy](https://numpy.org/)

+ La forma más común de utilización es importar la biblioteca con un alias:

In [1]:
import numpy as np

## ndarray

En el núcleo de Numpy está el <span style="color:magenta">ndarray</span>, donde <span style="color:magenta">nd</span> es por n-dimensional. Entonces un <span style="color:magenta">ndarray</span> es un arreglo multidimensional de <span style="color:magenta">elementos del mismo tipo</span>. (Es una lista con elementos del mismo tipo que se ejecuta a mayor velocidad que las listas normales de Python)

### Creación

In [ ]:
# Ejemplo: Numpy 1
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [3]:
print(type(x))
print(x)

<class 'numpy.ndarray'>
[1 2 3 4 5]


### Atributos del ndarray

A la información del arreglo se puede acceder mediante distintos atributos del mismo:

+ <span style="color:magenta">x.ndim</span>: las dimensiones del arreglo.
+ <span style="color:magenta">x.size</span>: el tamaño total del arreglo
+ <span style="color:magenta">x.shape</span>: la forma del arreglo
+ <span style="color:magenta">x.dtype</span>: el tipo de cada uno de sus elementos

In [4]:
# Ejemplo: Numpy 2
import numpy as np
x = np.array([1, 2, 3, 4, 5], dtype='int32')

In [5]:
print(x.ndim)
print(x.size)
print(x.shape)
print(x.dtype)

1
5
(5,)
int32


### Tipos de datos

+ Numpy puede manejar distintos tipos de datos

Algunos de los tipos de datos mas comunes de Numpy son:

*dtype* | *Descripción* | *Rango*
---|---|---
<span style="color:yellow">np.int32</span> | <span style="color:limegreen">integer</span> | De -2147483648 a 2147483647
<span style="color:yellow">np.int64</span> | <span style="color:limegreen">integer</span> | De -9223372036854775808 a 9223372036854775807
<span style="color:yellow">np.uint32</span> | <span style="color:limegreen">unsigned integer</span> | de 0 a 4294967295
<span style="color:yellow">np.uint64</span> | <span style="color:limegreen">unsigned integer</span> | de 0 a 18446744073709551615
<span style="color:yellow">np.float32</span> | <span style="color:limegreen">float</span> | De -3.4028235e+38 a 3.4028235e+38
<span style="color:yellow">np.float64</span> | <span style="color:limegreen">float</span> | De -1.7976931348623157e+308 a 1.7976931348623157e+308

Para <span style="color:cyan">Numpy</span> <span style="color:limegreen">int</span> hace referencia a <span style="color:yellow">np.int64</span> y <span style="color:limegreen">float</span> hace referencia a <span style="color:yellow">np.float64</span>.

Al momento de la creación de un arreglo se puede especificar el tipo de datos deseado.

In [6]:
# Ejemplo Numpy 3
import numpy as np

# Genera un arreglo de enteros
a = np.array(range(10), dtype = 'int32')
print(a)
print(type(a))
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int32


In [7]:
# Genera un arreglo de flotantes
b = np.array(np.arange(0, 1, 0.1), dtype = 'float32')
print(b)
print(b.dtype)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
float32


In [8]:
# Convierte enteros en flotantes
c = a.astype(float)
print(c)
print(c.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


### ndarray versus listas

+ Si bien tienen puntos en común son diferentes.
+ Por cuestiones de rendimiento los <span style="color:magenta">ndarray</span> son mejores.
+ Se ejecutan aproximadamente 12 veces mas rápido.

In [9]:
# Ejemplo: Numpy 4.
# Suma de 10 millones de valores

import numpy as np

arreglo_lista = list(range(int(10e6)))
arreglo_nd = np.array(arreglo_lista)

In [10]:
%timeit sum(arreglo_lista)
%timeit arreglo_nd.sum()

124 ms ± 1.91 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.62 ms ± 165 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


<span style="color:limegreen">%timeit</span> es una [funcion magica](https://ipython.readthedocs.io/en/stable/interactive/magics.html) de IPython, la cual se puede utilizar para medir el tiempo en una parte particular de código (una sentencia o un metodo).

El formato de <span style="color:limegreen">%timeit</span> es:

> <span style="color:limegreen">%timeit [-n\<N\> -r\<R\> [-t|-c] -q -p\<P\> -o] sentencia</span>

+ <span style="color:yellow">N</span>: cantidad de repeticiones para la medición de tiempo
+ <span style="color:yellow">R</span>: numero de repeticiones, cada una de N iteraciones (por defecto 7).
+ <span style="color:yellow">t</span>: utiliza time.time de Unix para medir el tiempo
+ <span style="color:yellow">c</span>: utiliza time.clock de Windows para medir el tiempo
+ <span style="color:yellow">P</span>: utiliza una precisión de P digitos (por defecto 3)
+ <span style="color:yellow">q</span>: no muestra los resultados
+ <span style="color:yellow">o</span>: retorna un tipo TimeitResult que se puede almacenar en una variable. 

+ Como ya se explicó, es posible convertir una lista en un <span style="color:magenta">ndarray</span> en el momento de la creación.

+ También se puede convertir un <span style="color:magenta">ndarray</span> en una lista mediante el uso del método <span style="color:limegreen">tolist()</span>.

In [11]:
# Ejemplo: Numpy 5
import numpy as np

x = np.array([1, 2, 3, 4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [12]:
y = x.tolist()
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


### Matrices

+ Una matriz es un arreglo bidimensional.
+ Se puede usar lo ya estudiado para crear matrices.
+ Poseen los mismos atributos que los arreglos unidimensionales.

In [13]:
# Ejemplo: Numpy 6
import numpy as np

# Observar la especificación a través de una lista de listas
M = np.array([[1., 2, 3], [4, 5, 6], [7, 8, 9]])
print(M)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [14]:
print(M.ndim)
print(M.size)

2
9


In [15]:
print(M.shape)
print(M.dtype)

(3, 3)
float64


### Cambiando la forma

+ Se puede cambiar la forma de un arrelo multidimensional
+ Se utiliza la función <span style="color:limegreen">np.reshape()</span>

In [16]:
# Ejemplo: Numpy 7
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(f'a: {a}')
print(f'forma de a: {a.shape}')
print(a.ndim)

a: [ 1  2  3  4  5  6  7  8  9 10 11 12]
forma de a: (12,)
1


In [17]:
b = np.reshape(a, (4, 3))
print(f'b: {b}')
print(f'forma de b: {b.shape}')

b: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
forma de b: (4, 3)


In [18]:
# El -1 significa que el valor es inferido de la longitud del arreglo
c = np.reshape(a, (6, -1)) 
print(f'c: {c}')

c: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
d = np.reshape(a, (-1, 3))
print(f'd: {d}')

In [ ]:
e = np.reshape(a, (5, -1))
print(f'e: {e}')

### Almacenando Arrays

Python permite almacenar y recuperar los arreglos de la siguiente manera:

+ Formato binario: mediante el método <span style="color:limegreen">save()</span> y <span style="color:limegreen">load()</span> se puede guardar la estructura de datos en un archivo tipo <span style="color:magenta">".npy"</span> o leer desde él.

+ Formato de texto: Python proporciona el método <span style="color:limegreen">savetxt()</span> para almacenar una estructura de datos en un archivo de texto <span style="color:magenta">".csv"</span> y <span style="color:limegreen">loadtxt()</span> para leer información desde un archico.

In [19]:
# Ejemplo: Numpy 8
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(M)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
np.save('miMatriz.npy', M)
print(f'Archivo guardado...\n')

Archivo guardado...



In [ ]:
M_recargada = np.load('miMatriz.npy')
print(f'\nArchivo leído, contenido:\n{M_recargada}')

In [21]:
# Ejemplo: Numpy 9
import numpy as np

M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(M)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
print(f'Guardando el archivo...')
np.savetxt('miMatriz.csv', M, fmt='%d')

Guardando el archivo...


In [ ]:
print("\nLee el archivo: ")
M_recargada = np.loadtxt('miMatriz.csv', dtype=int)
print(M_recargada)

In [ ]:
# Desempaquetado de valores, argumento unpack transpone la matriz
col1, col2, col3 = np.loadtxt('miMatriz.csv', unpack = True, dtype = int)
print("\nMuestra las columnas: ")
print(col1)
print(col2)
print(col3)

### Funciones Predefinidas para la creación de arreglos

+ <span style="color:cyan">Numpy</span> ofrece una gran variedad de funciones para la creación de arreglos que simplifican el proceso de construcción.

**Valores fijos**

+ Ceros: <span style="color:limegreen">np.zeros((3, 4), dtype=int)</span>. Por defecto utiliza float64
+ Copia: <span style="color:limegreen">np.zeros_like(M)</span> donde M es un arreglo existente.
+ Unos: <span style="color:limegreen">np.ones((3, 4), dtype=int)</span>. Por defecto utiliza float64.
+ Copia: <span style="color:limegreen">np.ones_like(M)</span>, donde M es una matriz existente.
+ Full: <span style="color:limegreen">np.full((3, 4), 7)</span>, crea una matriz de 3 x 4 llena con 7.
+ Full like: igual que en elcaso de ceros y unos.
+ Identidad: <span style="color:limegreen">np.eye(5)</span>: crea una matriz identidad de 5 x 5 elementos
+ Diagonal: <span style="color:limegreen">np.diag(lista)</span>. Crea una matriz diagonal

In [ ]:
# Ejemplo: Numpy 10
import numpy as np

M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [ ]:
A = np.zeros((5, 4))
print(f'A:\n{A}')

In [ ]:
B = np.zeros_like(M)
print(f'B:\n{B}')

In [ ]:
C = np.ones((5, 4), dtype=float)
print(f'C:\n{C}')

In [ ]:
D = np.ones_like(M)
print(f'D: \n{D}')

In [ ]:
E = np.full((2, 2), 20.)
print(f'E: \n{E}')

In [ ]:
F = np.eye(4)
print(f'F:\n{F}')

In [ ]:
G = np.diag([10, 20, 30, 40, 50])
print(f'G:\n{G}')

### Generación de Valores Equiespaciados

+ Estas funciones permiten generar arreglos con valores equiespaciados o en intervalos definidos.

+ Valores enteros: <span style="color:limegreen">np.arange()</span>
+ Valores flotantes: <span style="color:limegreen">np.linspace()</span>
+ Valores aleatorios: 
    + <span style="color:limegreen">np.random.randint()</span> : enteros
    + <span style="color:limegreen">np.random.random()</span>: flotantes



+ Distribuciones de Probabilidad:
    + Normal: <span style="color:limegreen">np.random.normal()</span>
    + Muestra aleatoria: <span style="color:limegreen">np.random.choice()</span>

In [23]:
# Ejemplo: Numpy 11
import numpy as np

# Función np.arange para enteros
# Especificando límite superior
A = np.arange(21)
print(f'A:\n{A}')

A:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [24]:
# Especificando el límite inferior y el superior
A = np.arange(6, 60)
print(f'A:\n{A}')

A:
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]


In [25]:
# Especificando límite inferior, superior y el paso
A = np.arange(6, 60, 3)
print(f'A:\n{A}')

A:
[ 6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57]


In [ ]:

# Especificando límite inferior, superior y el paso flotante
A = np.arange(6, 16, .3)
print(f'A:\n{A}')

In [26]:
#Ejemplo: Numpy 12
# Función np.linspace para flotantes. Siempre incluye el límite superior
# Especificando límite inferior y superior
A = np.linspace(6, 60) # por defecto 50 valores
print(f'A:\n{A}')

A:
[ 6.          7.10204082  8.20408163  9.30612245 10.40816327 11.51020408
 12.6122449  13.71428571 14.81632653 15.91836735 17.02040816 18.12244898
 19.2244898  20.32653061 21.42857143 22.53061224 23.63265306 24.73469388
 25.83673469 26.93877551 28.04081633 29.14285714 30.24489796 31.34693878
 32.44897959 33.55102041 34.65306122 35.75510204 36.85714286 37.95918367
 39.06122449 40.16326531 41.26530612 42.36734694 43.46938776 44.57142857
 45.67346939 46.7755102  47.87755102 48.97959184 50.08163265 51.18367347
 52.28571429 53.3877551  54.48979592 55.59183673 56.69387755 57.79591837
 58.89795918 60.        ]


In [27]:
# Especificando límite inferior, superior y el total de elementos
A = np.linspace(6, 60, 20)
print(f'A:\n{A}')

A:
[ 6.          8.84210526 11.68421053 14.52631579 17.36842105 20.21052632
 23.05263158 25.89473684 28.73684211 31.57894737 34.42105263 37.26315789
 40.10526316 42.94736842 45.78947368 48.63157895 51.47368421 54.31578947
 57.15789474 60.        ]


In [ ]:
# Especificando un intervalo abierto [a, b)
A = np.linspace(6, 60, 20, endpoint = False)
print(f'A:\n{A}')

In [30]:
# Ejemplo: Numpy 13
# Numeros aleatorios
# Escalar Entero
A = np.random.randint(3, 30)
print(f'A:\n{A}')

A:
7


In [ ]:
# Vector de enteros
A = np.random.randint(3, 30, size = 9)
print(f'A:\n{A}')

In [ ]:
# Matriz de enteros
A = np.random.randint(3, 30, size = (3, 3))
print(f'A:\n{A}')

In [31]:
# Numeros flotantes
# En un intervalo abierto [0, 1)
A = np.random.random(15)
print(f'A:\n{A}')

A:
[0.39748333 0.08443124 0.95096364 0.16656419 0.07179342 0.99308387
 0.4532179  0.31903782 0.01706423 0.51632118 0.30336385 0.49420895
 0.90363241 0.54163351 0.39791397]


In [32]:
# En un intervalo abierto [a, b)
A = np.random.uniform(1, 100, size=9)
print(f'A:\n{A}')

A:
[33.04743743 40.25392006 76.48544342 91.49464837 51.35794521 38.09630096
 56.13572549 60.2553351  31.25914345]


In [33]:
# Ejemplo: Numpy 14

# Distribuciones de Probabilidad
# Distribución Normal (media=0, desv=5)
dist = np.random.normal(0, 5, size = 1_000_000)
print(f'Elementos: \n{dist[:20]}')
print(f'Media = {dist.mean()}')
print(f'Desviación = {dist.std()}')

Elementos: 
[-2.85658704  0.61773172 -5.44791123 -9.47543689  8.30873946  3.23311099
  3.99349702  8.28874903 17.22415326  6.4520729   1.91726639 -3.26723602
 -7.59704469 -3.55318943 -4.29019405 -0.86736212  2.62646746 -2.66175732
  4.29791756  5.86587211]
Media = -0.002019986341443132
Desviación = 5.0018551553467665


In [ ]:
# Muestra Aleatoria
moneda = np.random.choice(['cara', 'seca'], size = 1_000_000)
print(f'Tirada: \n{moneda[:20]}')
print(f"Cantidad de caras: {sum(moneda == 'cara')}")
print(f"Cantidad de secas: {sum(moneda == 'seca')}")

In [ ]:
# Muestra Aleatoria con probabilidades no uniformes (dado)
dado = np.random.choice(range(1, 7), size = 1_000_000, p = [.5, .1, .1, .1, .1, .1])
print(f'Tirada: \n{dado[:20]}')
print(f'Cantidad de tiradas en 1: {sum(dado == 1)}')
print(f'Cantidad de tiradas en 6: {sum(dado == 6)}')

### Constantes

<span style="color:cyan">Numpy</span> proporciona una serie de [constantes predefinidas](https://numpy.org/doc/stable/reference/constants.html) que facilitan su acceso y reutilización 

In [ ]:
# Ejemplo: Numpy 15
# Constantes
print(np.inf, '\n')

In [ ]:
print(np.nan, '\n')

In [ ]:
print(np.pi, '\n')

In [ ]:
print(np.e, '\n')

In [ ]:
print(np.log(-1), '\n')

### Manipulando Elementos

Los <span style="color:magenta">arreglos multidimensionales</span> de <span style="color:cyan">Numpy</span> están indexados por ejes (<span style="color:limegreen">axis</span>) que establecen la forma en la que se debe acceder a sus elementos

![Acceso a los elementos de arreglos en Numpy](./Figuras/numpy_elementos.png)

**Arreglos Unidimensionales**

+ Se accede al elemento con el operdor de indexación de Python (<span style="color:limegreen">[ ]</span>)
+ Al igual que las listas los elementos de un arreglo unidimensional se puede modificar
+ También, se puede borrar un elemento de un arreglo
+ La inserción de elementos también es posible.

In [ ]:
# Ejemplo: Numpy 16

# Elementos en arreglos unidimensionales
valores = np.array([10, 11, 12, 13, 14, 15])
print(f'Valores:\n{valores}\n')

In [ ]:
# Acceso a un elemento
print(f'valores[2]: {valores[2]}')
print(f'valores[-2]: {valores[-2]}')
print('-----------------\n')

In [ ]:
# Modificación
valores[0] = valores[1] + valores[4]
print(f'valores[0] modificado\nvalores:\n{valores}')
print('-----------------\n')

In [ ]:
# Borrado de elementos
q = np.delete(valores, 2)
print(f'Borrado:\nvalores:\n{valores}\nq: \n{q}')
print('-----------------\n')

In [ ]:
#inserción de elementos
q = np.append(valores, [16, 17, 18])
print(f'Insercion:\nvalores:\n{valores}\nq: {q}')
print('-----------------\n')

In [ ]:
#inserción de elementos
q = np.insert(valores, 1, [16, 17, 18])
print(f'Insercion:\nvalores:\n{valores}\nq: {q}')

### Arreglos Multidimensionales

+ Se puede acceder a un elemento del arreglo multidimensional a través del operador de indexación.
+ Existe un dieferencia en como maneja los arreglos multidimensionales <span style="color:cyan">Numpy</span> respecto a Python.
+ Al igual que con los arreglos unidimensionales los elementos se pueden modificar, borrar e insertar nuevos.
+ Todas estas funciones crean una copia del arreglo original. No es una copia profunda por lo que si se modifica la copia se modifica también el arreglo original.

In [ ]:
#Ejemplo: Numpy 17

# Arreglos Multidimensionales
valores = np.arange(1, 13).reshape(3, 4)
print(f'valores:\n{valores}')

In [ ]:
#Acceso a elementos individuales
print(f'valores[0, 0]: {valores[0, 0]}')
print(f'valores[-1, -1]: {valores[-1, -1]}')
print(f'valores[1, 2]: {valores[1, 2]}')

In [ ]:
# Acceso a multiples elementos
# # elementos [0, 1] y [2, 2]
print(f'Acceso a multiples elementos:\nelementos[0, 1] y [2, 2]: {valores[[0, 2], [1, 2]]}') 

In [ ]:
# Acceso a filas o columnas completas
print(f'Tercer fila: {valores[2]}') # tercer fila
print(f'Segunda columna: {valores[:, 1]}') # segunda columna

In [ ]:
# Acceso a subarreglos
print(valores)
print(f'Subarreglo:\n{valores[0:2, 0:2]}')
print(f'Subarreglo:\n{valores[0:2, [1, 3]]}')

In [ ]:
# Modificación de elementos
valores[0, 0] = 100
valores[1] = [55, 66, 77, 88]
valores[:, 2] = [30, 70, 110]
print(f'Arreglo modificado:\n{valores}')

In [ ]:
#Ejemplo: Numpy 18

# Borrado en arreglos multidimensionales
valores = np.arange(1, 13).reshape(3, 4)
print(f'Arreglo Original:\n{valores}')

In [ ]:
# Borra una fila
q = np.delete(valores, 0, axis=0) # Borra la primera fila
print(f'Matriz con primer fila borrada:\n{q}')

In [ ]:
# Borrado de columnas
q = np.delete(valores, (1, 3), axis=1) # Borra la segunda y cuarta columna
print(f'Matriz con la segunda y cuarta columna borrada\n{q}')

In [ ]:
# Insercion de elementos
valores = np.array([[1, 2], [3, 4]])
print(f'Arreglo Original:\n{valores}')

In [ ]:
# Insercion al final
q = np.append(valores, [[5, 6]], axis=0) # inserta una fila
print(f'Matriz con insercion de fila:\n{q}')

In [ ]:
p = np.append(valores, [[5], [6]], axis=1) # inserta una columna
print(f'Matriz con insercion de columna:\n{p}')

In [ ]:
# Insercion en posiciones arbitrarias
q = np.insert(valores, 0, [0, 0], axis=0) # inserta fila al principio
print(f'Matriz con insercion de fila arbitraria:\n{q}')

In [ ]:
p = np.insert(valores, 1, [0, 0], axis=1) # inserta una columna
print(f'Matriz con insercion de columna arbitraria:\n{p}')

### Combinando Arreglos (Apilado)

En algunas ocasiones es importante combinar dos o mas arreglos. Uno de los mecanismos que provee <span style="color:cyan">Numpy</span> es el <span style="color:magenta">apilado</span>, que puede ser:

+ Vertical: con el método <span style="color:limegreen">np.vstack()</span>
+ Horizontal: con el método <span style="color:limegreen">np.hstack()</span>

In [ ]:
# Ejemplo: Numpy 19

m1 = np.random.randint(1, 100, size=(3, 2))
m2 = np.random.randint(1, 100, size=(1, 2))
m3 = np.random.randint(1, 100, size=(3, 1))

In [ ]:
print("Matrices Originales:\n")
print(f'm1:\n{m1}')
print(f'm2:\n{m2}')
print(f'm3:\n{m3}')

In [ ]:
# Apilado Vertical
q = np.vstack((m1, m2))
print(f'Apilado vertical:\n{q}')

In [ ]:
# Apilado Horizontal
q = np.hstack((m1, m3))
print(f'Apilado horizontal:\n{q}')

### Repitiendo Elementos

+ <span style="color:magenta">Repetición por ejes (axis)</span>: En este caso el argumento <span style="color:magenta">repetición</span> indica el número de veces que se repite el arreglo completo por cada eje.

+ <span style="color:magenta">Repetición por elementos</span>: el argumento <span style="color:magenta">repetición</span> indica el número de veces que se repite cada elemento del arreglo.

In [ ]:
# Ejemplo: Numpy 20

valores = np.array([[1, 2], [3, 4], [5, 6]])
print(f'valores:\n{valores}')

In [ ]:
# Repetición por eje
q = np.tile(valores, 3)  # por 3 en columnas
print(f'Repeticion por eje (x3 en col):\nq:\n{q}')

In [ ]:
p = np.tile(valores, (2, 3))  # x 2 en filas x3 en columnas
print(f'Repeticion x 2 en filas y por 3 en columnas\np:\n{p}')

In [ ]:
# Repeticion por elementos
print(valores)
q = np.repeat(valores, 2)
print(f'Repeticion por cada elementos\nq: {q}')

In [ ]:
p = np.repeat(valores, 2, axis=0) # x 2 en filas
print(f'Repeticion x 2 en filas\np:\n{p}')

In [ ]:
r = np.repeat(valores, 3, axis=1) # x 3 en columnas
print(f'Repeticion por 3 en columnas\nr:\n{r}')

### Acceso por Diagonal

Es común acceder a elementos en una matriz (arreglo en general) tomando como referencia su diagonal.

+ Extracción de elementos por diagonal: <span style="color:limegreen">np.diag(arr, k)</span>. Posee un argumento <span style="color:limegreen">k</span> que especifica la distancia a la diagonal.

![Extracción](./Figuras/numpy_diagonal.png)

+ Modificación de elementos por diagonal: <span style="color:limegreen">np.diag_indices()</span> que devuelve los indices de los elementos de la diagonal principal. 
    + <span style="color:limegreen">np.triu_indices()</span> devuelve los índices de los elementos de la diagonal superior de una matriz.
    + <span style="color:limegreen">np.tril_indices()</span> devuelve los índices de los elementos de la diagonal inferior de una matriz.

In [ ]:
# Ejemplo: Numpy 21
valores = np.array([[73, 86, 90, 20], [96, 55, 15, 48], [38, 63, 96, 48], [13, 87, 32, 96]])
print(valores, '\n')

In [ ]:
# Extracción de elementos
for k in range(0, valores.shape[0]):
    print(f'k={k}', np.diag(valores, k = k))

In [ ]:
for k in range(0, valores.shape[0]):
    print(f'k={-k}', np.diag(valores, k = -k))

In [ ]:
# Modificación de elementos por diagonal
q = np.diag_indices(valores.shape[0])
print(q, '\n')

In [ ]:
valores[q] = 0
print(valores, '\n')

In [ ]:
# Ejemplo: Numpy 21b
import numpy as np

valores = np.array([[73, 86, 90, 20], [96, 55, 15, 48], [38, 63, 96, 48], [13, 87, 32, 96]])
print(valores , '\n')

In [ ]:
# Modificación de elementos por diagonal
q = np.triu_indices(valores.shape[0])
print(q, '\n')

In [ ]:
valores[q] = 0
print(valores ,'\n')

### Operaciones sobre Arreglos

#### Operaciones Lógicas

**Indexado Booleano**

+ El indexado booleano es una operación que permite conocer (a nivel de elemento) si un arreglo cumple o no determinada condición.

+ Permite la generación de máscaras que son importantes para la manipulación de imágenes.

+ Las condiciones pueden ser complejas e incorporar conectores lógicos del tipo <span style="color:limegreen">and (&)</span> y <span style="color:limegreen">or (|)</span>.

+ También puede ser útil obtener los índices del arreglo que cumplen determinada condición, para esto se utiliza el método <span style="color:limegreen">where()</span>

In [ ]:
# Ejemplo: Numpy 22
val = np.array([[60, 47, 34, 38], [43, 63, 37, 68], [58, 28, 31, 43], [32, 65, 32, 96]])
print(f'val:\n{val}')

In [ ]:
# Indexado Booleano
q = val > 50
print(f'q > 50:\n{q}')

In [ ]:
# Uso de una máscara
q = val[val > 50]
print(f'Uso de máscara:\nq:\n{q}')

In [ ]:
# Modificación de valores
val[val > 50] = -1
print(f'Modificacion de elementos\nval:\n{val}')

In [ ]:
# Predicados compuestos
val = np.array([[60, 47, 34, 38], [43, 63, 37, 68], [58, 28, 31, 43], [32, 65, 32, 96]])
print(f'Uso de predicados compuestos\n')
print(f'Uso de or:\nval: {(val < 25) | (val > 75)}') # Uso de or

In [ ]:
print(f'Uso de and:\nval:\n{(val > 25) & (val < 75)}') # Uso de and

In [ ]:
# Uso del método where()
idx = np.where(val > 50)
print(f'Indices:\nidx: {idx}')
print(f'val:\n{val[idx]}')

**Comparando Arreglos**

+ La comparación de arreglos se puede realizar utilizando el operador <span style="color:limegreen">==</span> como con cualquier objeto de Python. 

+ El resultado debe entenderse que la evaluación es a nivel de elemento.

+ También se puede utilizar la función <span style="color:limegreen">np.array_equal(m1, m2)</span> que compara arreglos en su totalidad.

In [ ]:
# Ejemplo: Numpy 23
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[1, 2], [3, 4]])

In [ ]:
print(f'Son iguales?:\n{m1 == m2}')

In [ ]:
print("Son iguales: ", np.array_equal(m1, m2))

### Operaciones de Conjuntos

Las operaciones de conjuntos, <span style="color:magenta">union</span>, <span style="color:magenta">intersección</span> y <span style="color:magenta">diferencia</span> se pueden utilizar con arreglos.

In [ ]:
# Ejemplo: Numpy 24
x = np.array([9, 4, 11, 3, 14, 5, 13, 12, 7, 14])
y = np.array([17, 9, 19, 4, 18, 4, 7, 13, 11, 10])
print(f'Conjuntos:\nx: {x}\ny: {y}\n')

In [ ]:
# Union
q = np.union1d(x, y)
print(f'Union de conjuntos:\nq: {q}')

In [ ]:
# Intersección
q = np.intersect1d(x, y)
print(f'Interseccion de conjuntos:\nq: \n{q}')

In [ ]:
# Diferencia
q = np.setdiff1d(x, y)
print(f'Diferencia:\nq:\n{q}')

### Ordenación de Arreglos

Numpy posee dos formas para ordenar arreglos:

+ <span style="color:magenta">ordenacion "in-situ"</span> que es destructiva, es decir se modifica el arreglo original.
+ <span style="color:magenta">ordenación que no es destructiva</span>.

<span style="color:limegreen">np.sort(array, axis=-1, kind=None, order=None)</span>

donde:
+ <span style="color:limegreen">array</span> es el arreglo a ordenar.
+ <span style="color:limegreen">axis</span> es el eje a lo large del cual se desea ordenar.
+ <span style="color:limegreen">kind</span> especifica el algoritmo de ordenación (<span style="color:yellow">quicksort</span> por defecto, <span style="color:yellow">mergesort</span>, <span style="color:yellow">heapsort</span>, <span style="color:yellow">stable</span>)

In [ ]:
# Ejemplo: Numpy 25

# Arreglos Unidimensionales
x = np.array([23, 24, 92, 88, 75, 68, 12, 91, 94, 24, 9, 21, 42, 3, 66])
print(f'Arreglo original: {x}\n')

In [ ]:
# Ordenación No destructuva
q = np.sort(x)
print(f'Arreglo ordenado: {q}\n')
print(f'Arreglo original: {x}\n')

In [ ]:
# Ordenación destructiva
x.sort()
print(f'Arreglo modificado: {x}\n')

In [ ]:
# Arreglos Multidimensionales
x = np.array([[52, 23, 90, 46], [61, 63, 74, 59], [75, 5, 58, 70], [21, 7, 80, 52]])
print(f'Arreglo original:\n{x}')

In [ ]:
# No destructuva.
# Tambien existe las correspondientes ordenaciones destructivas
q = np.sort(x, axis=1)
print(f'Nuevo Arreglo Ordenado por filas:\n{q}')

In [ ]:
q = np.sort(x, axis=0)
print(f'Arreglo Modificado por columnas:\n{q}')

### Contando Valores

Los siguientes métodos dan la posibilidad de contar el número de valores que existen en una arreglo en base a cierto criterio

+ Valores únicos: se usa la función <span style="color:limegreen">np.unique()</span>
+ Valores distintos de cero: <span style="color:limegreen">np.count_nonzero()</span>

In [ ]:
# Ejemplpo: NUmpy 26
x = np.random.randint(1, 11, size=10)
print(f'x[:20]:\n{x[:20]}')

In [ ]:
# Valores únicos
q = np.unique(x)
print(f'Valores unicos: {q}')

In [ ]:
# Valores únicos
q = np.unique(x, return_index=True)
print(f'Valores unicos: {q}')

In [ ]:
# Valores únicos (incluye frecuencias)
q = np.unique(x, return_counts=True)
val, frec = q
print(f'Valores unicos con frecuencia:\n{val}\n{frec}')

In [ ]:
# Valores distintos de cero
q = np.count_nonzero(x)
print(f'Valores distintos de cero: {q}')

In [ ]:
# Valores distintos de cero (incluyendo condición)
q = np.count_nonzero(x > 5)
print(f'Valores distintos de cero y mayor a 5: {q}')

### Operaciones Aritméticas

+ Una de las grandes ventajas del uso de arreglos numéricos en <span style="color:cyan">NumPy</span> es la posibilidad de trabajar con ellos como si fueran objetos «simples» pero aprovechando la aritmética vectorial. 

+ Esto redunda en una mayor eficiencia y rapidez de cómputo.

**Operaciones Aritmeticas con iguales dimensiones**

Cuando se opera con arreglos de dimensiones iguales, las operaciones aritméticas se realizan elemento a elemento y el resultado posee la misma dimensión.

In [34]:
# Ejemplo: Numpy 27
m1 = np.array([[21, 86, 45], [31, 36, 78], [31, 64, 70]])
m2 = np.array([[58, 67, 17], [99, 53, 9], [92, 42, 75]])
print(f'm1:\n{m1}\n\nm2:\n{m2}')

m1:
[[21 86 45]
 [31 36 78]
 [31 64 70]]

m2:
[[58 67 17]
 [99 53  9]
 [92 42 75]]


In [35]:
# Suma elemento a elemento
A = m1 + m2
print(f'S = \n{A}')

S = 
[[ 79 153  62]
 [130  89  87]
 [123 106 145]]


In [ ]:
# Resta eleento a elemento
A = m1 - m2
print(f'R = \n{A}')

In [ ]:
# Multiplicación elemento a elemento
A = m1 * m2
print(f'M = \n{A}')

In [ ]:
# División Flotante
A = m1 / m2
print(f'D =\n{A}')

In [ ]:
# División Entera
A = m1 // m2
print(f'DE =\n{A}')

**Operaciones Aritméticas con distintas dimensiones**

Cuando se opera entre arreglos con dimensiones diferentes, siempre y cuando se cumplan ciertas restricciones en tamaños de filas y/o columnas, lo que se produce es un «broadcasting» (o difusión) de los valores.

+ <span style="color:magenta">Suma con arreglos "fila"</span>
+ <span style="color:magenta">Suma con arreglos "columna"</span>

En el caso de no coincidir las dimensiones se produce una excepción del tipo <span style="color:limegreen">ValueError</span>.

**Operaciones entre arreglos y escalares**

En este caso el <span style="color:magenta">escalar</span> es difundido en todo el arreglo.

In [ ]:
# Ejemplo: Numpy 28
x = np.array([[9, 8, 1], [7, 6, 7]])
y = np.array([[2, 3, 6]])
z = np.array([[1], [6]])
print(f'x:\n{x}\ny:\n{y}\nz:\n{z}')

In [ ]:
# Suma con arreglos fila
a = x + y
print(f'Suma con arreglo fila (x + y):\n{a}')

In [ ]:
# Suma con arreglos columna
a = x + z
print(f'Suma con arreglo columna (x + z):\n{a}')

In [ ]:
# Operaciones con escalares
a = x + 5
print(f'Suma con un escalar:\n{a}')

In [ ]:
a = x - 5
print(f'Resta con un escalar:\n{a}')

In [ ]:
a = x * 5
print(f'Producto con un escalar:\n{a}')

In [ ]:
a = x / 5
print(f'División por un escalar:\n{a}')

In [ ]:
a = x ** 5
print(f'Exponenciacion por un escalar:\n{a}')

### Operaciones Unarias

En <span style="color:cyan">Numpy</span> existen varias funciones que operan sobre un único arreglo.

**Funciones Universales**

+ Las funciones universales <span style="color:limegreen">ufunc</span> operan sobre arreglos <span style="color:magenta">elemento a elemento</span>.

+ Existen muchas [funciones universales](https://numpy.org/doc/stable/reference/ufuncs.html#) en <span style="color:cyan">Numpy</span>.

+ Analizaremos algunas de ellas.

In [ ]:
#Ejemplo: Numpy 29

# Funciones Universales
A = np.array([[48.32, 24.90, 77.50], [77.82, 22.54, 65.11], [5.54, 59.07, 62.53]])
print(f'Arreglo original:\n{A}')

In [ ]:
# Raiz Cuadrada
x = np.sqrt(A)
print(f'Raiz Cuadrada:\n{x}')

In [ ]:
# Seno
x = np.sin(A)
print(f'Seno:\n{x}')

In [ ]:
# Techo
x = np.ceil(A)
print(f'Redondeo hacia arriba:\n{x}')

In [ ]:
# Piso
x = np.floor(A)
print(f'Redondeo hacia abajo:\n{x}')

In [ ]:
# Logaritmo Natural (ver log10)
x = np.log(A)
print(f'Logaritmo Natural:\n{x}')

**Funciones Especiales**

+ <span style="color:cyan">NumPy</span> nos permite aplicar cualquier función sobre un arreglo <span style="color:magenta">reduciendo</span> el resultado por alguno de sus ejes. Esto abre una amplia gama de posibilidades.

In [ ]:
# Ejemplo: Numpy 30
x = np.array([[8, 2, 7], [2, 0, 6], [6, 3, 4]])
print(x, '\n')

In [ ]:
# Suma por columnas
a = np.sum(x, axis = 0)
print(a, '\n')

In [ ]:
# Suma por filas
a = np.sum(x, axis = 1)
print(a, '\n')

In [ ]:
# Producto por columnas
a = np.prod(x, axis = 0)
print(a, '\n')

In [ ]:
# Producto por filas
a = np.prod(x, axis = 1)
print(a, '\n')

**Funciones Estadísticas**

+ <span style="color:cyan">Numpy</span> ofrece una variada gama de [funciones estadísticas](https://numpy.org/doc/stable/reference/routines.statistics.html) para ser aplicadas sobre arreglos.

+ Analicemos algunas de ellas.

In [ ]:
# Ejemplo: Numpy 31
dist = np.random.normal(0, 5, size=(50, 50))
print(f'{dist}\n')

In [ ]:
# Media
a = np.mean(dist)
print(a, '\n')

In [ ]:
# Desviación estandard
a = np.std(dist)
print(a, '\n')

In [ ]:
# Mediana
a = np.median(dist)
print(a, '\n')

**Máximos y Mínimos**

+ <span style="color:cyan">Numpy</span> ofrece algunas funciones para calcular valores máximos y mínimos en arreglos

+ También es posible obtener los <span style="color:magenta">índices</span> de aquellos elementos con valores <span style="color:magenta">máximos</span> o <span style="color:magenta">mínimos</span>. Funciones <span style="color:limegreen">argmax()</span> y <span style="color:limegreen">argmin()</span>.

In [ ]:
# Ejemplo: Numpy 32
x = np.random.randint(1, 100, size=(5, 5))
print(f'Arreglo Original:\n{x}')

In [ ]:
# Minimo
y = np.min(x)
print(f'Valor minimo: {y}')

In [ ]:
y = np.min(x, axis=0)
print(f'valores minimos en el eje 0: {y}')

In [ ]:
y = np.min(x, axis=1)
print(f'valores minimos en el eje 1: {y}')

In [ ]:
# Maximo
y = np.max(x)
print(f'valor maximo: {y}')

In [ ]:
y = np.max(x, axis=0)
print(f'valores maximos en el aje 0: {y}')

In [ ]:
y = np.max(x, axis=1)
print(f'valores maximos en el aje 1: {y}')

In [ ]:
# Indices
idx = np.argmax(x, axis=0)
print(f'indices de valores maximos en el eje 0: {idx}')

In [ ]:
print(f'valores maximos en los indices: {x[idx, range(x.shape[1])]}')

### Vectorizando Funciones

Una de las ventajas de trabajar con arreglos numéricos en <span style="color:cyan">NumPy</span> es aprovechar la optimización que se produce a nivel de la propia estructura de datos.

Por ejemplo: Si se desea realizar el siguiente cálculo entre las matrices $A$ y $B$:

$$
A_{ij} * B_{ij} = \left\{
\begin{matrix}
A_{ij} + B_{ij}, \text{  si } A_{ij} \gt B_{ij}\\
A_{ij} - B_{ij}, \text{  si } A_{ij} \lt B_{ij}\\
0, \text{  en otro caso}
\end{matrix}
\right.
$$

In [ ]:
# Ejemplo: Numpy 33
import numpy as np

def mifuncion(a, b):
    if a > b:
        return a + b
    elif a < b:
        return a - b
    else:
        return 0

In [ ]:
def mia(a, b, r):
    for i in range(a.shape[0]): 
        for j in range(a.shape[1]): 
            r[i, j] = mifuncion(a[i, j], b[i, j])

In [ ]:
A = np.random.randint(-100, 100, size=(3000, 3000))
B = np.random.randint(-100, 100, size=(3000, 3000))

In [ ]:
resultado = np.zeros_like(A)

In [ ]:
%timeit mia(A,B, resultado)

In [ ]:
A = []
B = []
resultado = []
# libero la memoria por que las matrices son grandes

**Mejorando el rendimiento con funciones vectorizadas**

+ Con un pequeño detalle podemos mejorar el rendimiento de la función que hemos diseñado anteriormente. Se trata de utilizar un decorador denominado <span style="color:limegreen">np.vectorize</span> con lo que se estará otorgándole un comportamiento distinto y enfocado al procesamiento de arreglos numéricos.

+ Dado que ahora ya se trata de una función vectorizada se puede aplicar directamente a las matrices de entrada.

In [ ]:
# Ejemplo: Numpy 34
import numpy as np

@np.vectorize
def mifuncion(a, b):
    if a > b:
        return a + b
    elif a < b:
        return a - b
    else:
        return 0

In [ ]:
A = np.random.randint(-100, 100, size=(3000, 3000))
B = np.random.randint(-100, 100, size=(3000, 3000))

In [ ]:
%timeit mifuncion(A, B)

In [ ]:
A = []
B = []
# libero la memoria

## Algebra Lineal

Numpy posee una sección dedicada al [Algebra Lineal](https://numpy.org/doc/stable/reference/routines.linalg.html#module-numpy.linalg)

**Producto de Matrices**

+ Se utiliza la función <span style="color:limegreen">np.dot(m1, m2)</span> para realizar el producto clásico de matrices.
+ También se puede utilizar el operador <span style="color:limegreen">@</span> para multiplicar matrices (a partir de Python v3.5).
+ Otra función que se prefiere utilizar es <span style="color:limegreen">np.matmul</span>

In [ ]:
# Ejemplo: Numpy 35
import numpy as np

m1 = np.array([[1, 8, 4], [8, 7, 1], [1, 3, 8]])
m2 = np.array([[1, 5, 7], [9, 4, 2], [1, 4, 2]])
print(f'm1:\n{m1}\nm2:\n{m2}')

In [ ]:
q = np.dot(m1, m2) # Producto clásico de matrices
print(f'Producto con np.dot:\n{q}')

In [ ]:
# Usando el operador @
print(f'Usando el operador @:\n{m1 @ m2}')

In [ ]:
q = np.matmul(m1, m2)
print(f'Producto de matrices con np.matmul:\n{q}')

**Calculo del Determinante de un Matriz**

+ Para calcular el <span style="color:magenta">determinante</span> de una matriz se utiliza la función <span style="color:limegreen">np.linalg.det(m)</span>.

**Inversa de una Matriz**

+ Se utiliza la función <span style="color:limegreen">np.linalg.inv(m)</span>.

**Traspuesta de una Matriz**

+ El cálculo de la <span style="color:magenta">traspuesta</span> de una matriz es directo.

**Elevar una Matriz a una potencia**

+ Se utiliza la función <span style="color:limegreen">np.linalg.matrix_power(m, pot)</span>.

In [ ]:
# Ejemplo: Numpy 36
import numpy as np

m1 = np.array([[1, 8, 4], [8, 7, 1], [1, 3, 8]])
print(f'm1:\n{m1}')

In [ ]:
# Calculo del determinante
det = np.linalg.det(m1)
print(f'Determinante: {det}')

In [ ]:
# Calculo de la matriz inversa
m1_inv = np.linalg.inv(m1)
print(f'Inversa de una matriz:\n{m1_inv}')

In [ ]:
# Comprobación
iden = np.matmul(m1, m1_inv)
print(f'Comprobación m1 @ inv)m1):\n{iden}')

In [ ]:
print(m1)
# Matriz Traspuesta
print(f'Matriz traspuesta:\n{m1.T}')

In [ ]:
# Matriz elevada al cubo
print(f'Matriz eleveada al cubo:\n{np.linalg.matrix_power(m1, 3)}')

### Sistemas de ecuaciones lineales

<span style="color:cyan">Numpy</span> también permite resolver sistemas de ecuaciones lineales.

Por ejemplo:
Suponer el siguiente sistema lineal

$$
\left \{ \begin{matrix}
x_1 + 2 x_3 = 1\\
x_1 - x_2 = -2\\
x_2 + x_3 = -1
\end{matrix}\right. \rightarrow
\begin{pmatrix}
1 & 0 & 2\\
1 & -1 & 0\\
0 & 1 & 1 \end{pmatrix}
\begin{pmatrix}
x_1\\
x_2\\
x_3
\end{pmatrix} = \begin{pmatrix}
1\\
-2\\
-1
\end{pmatrix} \rightarrow
\mathbf{A} \mathbf{X} = \mathbf{B}
$$

$$
x = A^{-1}B
$$

La solución a este sitema se logra aplicando la función *np.solve(A, B)*

In [ ]:
# Ejemplo: Numpy 37
A = np.array([[1, 0, 2], [1, -1, 0], [0, 1, 1]])
B = np.array([1, -2, -1]).reshape(-1, 1)

In [ ]:
print(f'A:\n{A}')

In [ ]:
print(f'B:\n{B}')

In [ ]:
X = np.linalg.solve(A, B)
print(f'X:\n{X}')

In [ ]:
#Comprobación
print(f'A @ X:\n{A @ X}')

In [ ]:
# Ejemplo: Numpy 38
A = np.array([[1, 0, 2], [1, -1, 0], [0, 1, 1]])
B = np.array([1, -2, -1]).reshape(-1, 1)

In [ ]:
print(f'A:\n{A}')

In [ ]:
print(f'B:\n{B}')

In [ ]:
# Implementa X = inv(A) @ B
X = np.dot(np.linalg.inv(A), B)
print(f'X:\n{X}')

In [ ]:
#Comprobación
print(f'A @ X:\n{A @ X}')

[+info Numpy](https://numpy.org/doc/stable/reference/index.html#reference)